services:
  # --- HESK (MySQL 8.0) ---
  hesk-db:
    container_name: hesk-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${HESK_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${HESK_DB_NAME}
      - MYSQL_USER=${HESK_DB_USER}
      - MYSQL_PASSWORD=${HESK_DB_PASSWORD}
    volumes:
      - hesk-db-data:/var/lib/mysql
    networks:
      - hesk-back

  hesk-web:
    container_name: hesk-web
    build: ./hesk-docker
    env_file: .env
    ports:
      - "8081:80"
    volumes:
      - ./hesk:/var/www/html
    depends_on:
      - hesk-db
    networks:
      - hesk-back
      - hesk-front

  # --- ZABBIX (PostgreSQL 16 + Versión 6.0 LTS) ---
  zabbix-db:
    container_name: zabbix-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - zabbix-back    

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-6.0-latest
    env_file: .env
    networks:
      - zabbix-back    

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    env_file: .env
    depends_on:
      - zabbix-db
    networks:
      - zabbix-back
      - zabbix-front    

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.0-latest
    env_file: .env
    ports:
      - "80:8080"
    depends_on:
      - zabbix-db
      - zabbix-server
    networks:
      - zabbix-back
      - zabbix-front    

networks:
  hesk-front:
    driver: bridge
  hesk-back:
    driver: bridge
    internal: true

  zabbix-front:
    driver: bridge
  zabbix-back:
    driver: bridge
    internal: true

volumes:
  zabbix-db-data:
  hesk-db-data: