name: CI/CD HESK Categories
on:
  push:
    paths:
      - 'categories.txt'

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync Categories
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: "hesk_db"
        run: node sync_categories.js